### ISSUE TITLE
Multi module/target application with the useKeyAsValue as true

### ISSUE THREAD

**Issue by aliunco** [farzadshbfn/Styled#2]
I believe there is a bug in this scenario: 
If we use multiple bundles and in our main scheme (`LocalizedString.DefaultScheme`) we set the `useKeyAsValue` as `true`, then the resolver will not look inside the other bundles cause the `main` bundle has a value which is the `key` value itself. 

in line 335 of `LocalizedString.swift` maybe it's better to change the
```swift
$0.string(for: localizedString) ?? String.localized(localizedString, in: bundle, useKeyAsValue: useKeyAsValue, table: table)
```

to 
```swift
String.localized(localizedString, in: bundle, useKeyAsValue: useKeyAsValue, table: table) ?? $0.string(for: localizedString)
```

**Comment by farzadshbfn** [comment]
By changing it to the second version, `LocalizedStringScheme` will lose point of control. Since `.bundled(_)` LocalizedStrings will always be loaded from bundle and `Scheme` is useless (which is in contradiction with the definition of `LocalizedStringScheme`).

`NoScheme` is also defined in each `Styled.Item` for such purpose. Using `LocalizedString.NoScheme` will fix the problem.
